package com.oreo.mcommonjobs.Activtity;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.android.volley.Request;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.oreo.mcommonjobs.R;
import com.oreo.mcommonjobs.RequestController;
import com.oreo.mcommonjobs.URLPath;
import com.oreo.mcommonjobs.UserSession;

import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

//import com.oreo.mcommonjobs.Controllers.SendConfirmationSms;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.Random;

/**
 * The TwilioAuthenticationActivity has a responsibility of sending a confirmation code to the user
 * via sms and the user has to input that code into the textfield in order to be logged in
 * @author  Sam
 * @author  Ali
 * @version 1.0
 * @since   2017-03-13
 */

public class TwilioAuthenticationActivity extends AppCompatActivity {

    private EditText editText_confirmation, editText_phoneNumber;
    private Button button_submit_confirmation, button_sendConfirmationCode;

    private Random randomConfirmationCodeGenerator;

    private int inputConfirmation, generatedConfirmation;
    private String phonenumber;

    /**
     * this method instantiates every UI element of this activity and sets the onclick listeners on the buttons
     * @param savedInstanceState
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        /*
        setContentView(R.layout.activity_twilio_authentication);

        randomConfirmationCodeGenerator = new Random();

        editText_confirmation = (EditText) findViewById(R.id.editText_confirmation_number);
        editText_phoneNumber = (EditText) findViewById(R.id.editText_phoneNumber);
        button_submit_confirmation = (Button) findViewById(R.id.button_submit_confirmation);
        button_sendConfirmationCode = (Button) findViewById(R.id.button_sendConfirmationCode);

        button_sendConfirmationCode.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //Prevents the app from crashing in case the user clicks a button without entering it's phone number
                if(editText_phoneNumber.getText().toString().matches("")){
                    Toast.makeText(getApplicationContext(), "Please enter your phone number.", Toast.LENGTH_LONG).show();
                }
                else{
                    //Generating a random confirmation code between 100000 and 999999.
                    generatedConfirmation = randomConfirmationCodeGenerator.nextInt(999999 - 100000) + 100000;

                    phonenumber = editText_phoneNumber.getText().toString();

                    //Using a SendConfirmationSms object to send the generated confirmation code to a specified phone number.
                    //SendConfirmationSms smsAuthentication = new SendConfirmationSms(getApplicationContext());
                    //smsAuthentication.execute(Integer.toString(generatedConfirmation), phonenumber);
                }
            }
        });

        button_submit_confirmation.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                //Prevents the app from crashing in case the user clicks a button without entering it's confirmation number.
                if(editText_confirmation.getText().toString().matches("")){
                    Toast.makeText(getApplicationContext(), "Please enter your confirmation code.", Toast.LENGTH_LONG).show();
                }
                else{
                    inputConfirmation = Integer.parseInt(editText_confirmation.getText().toString());

                    //Comparing the input confirmation code and the confirmation code generated by the app.
                    if(inputConfirmation == generatedConfirmation){
                        Toast.makeText(getApplicationContext(), "Confirmation codes matched!", Toast.LENGTH_SHORT).show();

                        // User Type Request
                        JsonObjectRequest jsonRequest = new JsonObjectRequest(Request.Method.GET, URLPath.getUserType, null,
                                new Response.Listener<JSONObject>() {
                                    @Override
                                    public void onResponse(JSONObject response) {
                                        // Add user type to session
                                        UserSession session = UserSession.getInstance();
                                        try {
                                            session.setUserType(response.get("type"));
                                        } catch (JSONException e) {
                                            // Encountered Error
                                            e.printStackTrace();
                                        }
                                    }
                                },
                                new Response.ErrorListener() {
                                    @Override
                                    public void onErrorResponse(VolleyError error) {
                                        // Handle error
                                    }
                                 });

                        // First-time user check
                        JsonObjectRequest frequencyRequest = new JsonObjectRequest(Request.Method.GET, URLPath.checkFirstTimeUse, null,
                                new Response.Listener<JSONObject>() {
                                    @Override
                                    public void onResponse(JSONObject response) {
                                        if(response.get("first-time")){
                                            // Create user in the database (using google firstname, last name)
                                            // First-time user, need more details (name, ...)
                                            startActivity(new Intent(getApplicationContext(), UserNameSetupActivity.class));
                                        }
                                        else{

                                            // Go to Profile Menu in order to choose your profile
                                            startActivity(new Intent(getApplicationContext(), ProfileMenuActivity.class));
                                        }
                                    }
                                },
                                new Response.ErrorListener() {
                                    @Override
                                    public void onErrorResponse(VolleyError error) {
                                        // Handle error
                                    }
                                });

                        RequestController.getInstance(getApplicationContext()).addToRequestQueue(jsonRequest);
                        RequestController.getInstance(getApplicationContext()).addToRequestQueue(frequencyRequest);

                    }
                    else{
                        Toast.makeText(getApplicationContext(), "Confirmation codes didn't match!", Toast.LENGTH_SHORT).show();
                    }
                }
            }

        });

        */
    }



}
